name: Linter

on:
  pull_request:
    branches:
      - "*"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    env:
      TURSO_DB_URL: .
      BETTER_AUTH_URL: .
      BETTER_AUTH_SECRET: .
      GOOGLE_CLIENT_ID: .
      GOOGLE_CLIENT_SECRET: .
      DISCORD_CLIENT_ID: .
      DISCORD_CLIENT_SECRET: .
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun run lint
